<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Barangay_Service_Appointment_System</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
    