Imports MySql.Data.MySqlClient
Imports System.IO
Imports System.Text.RegularExpressions
Imports System.Runtime.InteropServices

Public Class frmcreateuser
    Private Const EM_SETCUEBANNER As Integer = &H1501
    Private Const CB_SETCUEBANNER As Integer = &H1703
    <DllImport("user32.dll", CharSet:=CharSet.Auto)>
    Private Shared Function SendMessage(hWnd As IntPtr, msg As Integer, wParam As Integer, <MarshalAs(UnmanagedType.LPWStr)> lParam As String) As IntPtr
    End Function

    Private editingUserID As Integer? = Nothing
    Private editingSourceTable As String = "users"
    Private isFormLoading As Boolean = False ' ✅ PREVENTS VALIDATION CRASHES DURING LOAD

    Public Sub New(ByVal userID As Integer, Optional ByVal srcTable As String = "users")
        InitializeComponent()
        editingUserID = userID
        editingSourceTable = srcTable
    End Sub

    Public Sub New()
        InitializeComponent()
    End Sub

    Private Sub frmcreateuser_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        isFormLoading = True ' Start loading flag

        InitializePlaceholders()

        If editingUserID.HasValue AndAlso editingSourceTable = "admin" Then
            cboDepartment.Visible = False
            lblRoleError.Visible = False
            txtEmail.Visible = False
            lblEmailError.Visible = False
            txtContactNo.Visible = False
            lblContactNoError.Visible = False
            cboAssignedOffice.Visible = False
            lblAssignedOfficeError.Visible = False
        Else
            cboDepartment.Visible = True
            lblRoleError.Visible = True
            txtEmail.Visible = True
            lblEmailError.Visible = True
            txtContactNo.Visible = True
            lblContactNoError.Visible = True
            cboAssignedOffice.Visible = True
            lblAssignedOfficeError.Visible = True
            LoadDepartmentsCombo()
            LoadSatelliteOfficesCombo()
        End If

        LoadRolesFromDatabase()

        If editingUserID.HasValue Then
            LoadUserDataForEdit()
            btnSubmit.Text = "Update User"
            Me.Text = "Edit User Information"
        Else
            txtUsername.Tag = "AutoGenerated"
            GenerateStaffCode()
            Me.Text = "Create New User"
        End If

        ClearAllValidationLabels()
        isFormLoading = False ' End loading flag
    End Sub

    Private Sub InitializePlaceholders()
        SendMessage(txtLastname.Handle, EM_SETCUEBANNER, 0, "DELA CRUZ")
        SendMessage(txtFirstname.Handle, EM_SETCUEBANNER, 0, "JUAN")
        SendMessage(txtUsername.Handle, EM_SETCUEBANNER, 0, "juandela01")
        SendMessage(txtEmail.Handle, EM_SETCUEBANNER, 0, "juan.delacruz@gmail.com")
        SendMessage(txtContactNo.Handle, EM_SETCUEBANNER, 0, "0912-345-6789")
        SendMessage(txtPassword.Handle, EM_SETCUEBANNER, 0, "Min. 6 chars: Aa123")
        SendMessage(txtConfirmPass.Handle, EM_SETCUEBANNER, 0, "Re-enter password")
        SendMessage(cboDepartment.Handle, CB_SETCUEBANNER, 0, "Select Department")
        SendMessage(cboAssignedOffice.Handle, CB_SETCUEBANNER, 0, "Select Satellite Office")
        SendMessage(cboRole.Handle, CB_SETCUEBANNER, 0, "Select Role")
    End Sub

    Private Sub LoadSatelliteOfficesCombo()
        Try
            connection()
            Dim sql = "SELECT id, satellite_office_number, facility_name, location_details " &
                      "FROM brgy_putatan_satellite_offices ORDER BY facility_name ASC"
            Dim dtOffices As New DataTable()
            Using localCmd As New MySqlCommand(sql, cn)
                Using adapter As New MySqlDataAdapter(localCmd)
                    adapter.Fill(dtOffices)
                End Using
            End Using
            If cboAssignedOffice IsNot Nothing Then
                cboAssignedOffice.DataSource = dtOffices
                cboAssignedOffice.DisplayMember = "facility_name"
                cboAssignedOffice.ValueMember = "id"
                cboAssignedOffice.SelectedIndex = -1
            End If
        Catch ex As Exception
            MsgBox("Error loading Satellite Offices: " & ex.Message, MsgBoxStyle.Exclamation)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub LoadDepartmentsCombo()
        Try
            connection()
            Dim sql = "SELECT DepartmentName FROM departments WHERE IsActive = 1 ORDER BY DepartmentName ASC"
            Dim dtDept As New DataTable()
            Using localCmd As New MySqlCommand(sql, cn)
                Using adapter As New MySqlDataAdapter(localCmd)
                    adapter.Fill(dtDept)
                End Using
            End Using
            If cboDepartment IsNot Nothing Then
                cboDepartment.DataSource = dtDept
                cboDepartment.DisplayMember = "DepartmentName"
                cboDepartment.ValueMember = "DepartmentName"
                cboDepartment.SelectedIndex = -1
            End If
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub LoadRolesFromDatabase()
        If cboRole Is Nothing Then Exit Sub
        cboRole.Items.Clear()
        Try
            connection()
            Dim sql = "SELECT RoleName FROM user_roles ORDER BY RoleName ASC"
            Using cmd As New MySqlCommand(sql, cn)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    While dr.Read()
                        cboRole.Items.Add(dr("RoleName").ToString().ToUpper())
                    End While
                End Using
            End Using
        Catch ex As Exception
            MsgBox("Error loading Roles: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Function IsValidRole(roleName As String) As Boolean
        If String.IsNullOrWhiteSpace(roleName) Then Return False
        Try
            connection()
            Dim sql = "SELECT COUNT(*) FROM user_roles WHERE UPPER(RoleName) = UPPER(@rname)"
            Using cmd As New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@rname", roleName.Trim())
                Return Convert.ToInt32(cmd.ExecuteScalar()) > 0
            End Using
        Catch ex As Exception
            Return False
        Finally
            CloseConnection()
        End Try
    End Function

    Private Sub LoadUserDataForEdit()
        Try
            connection()
            Dim idCol As String = If(editingSourceTable = "admin", "AdminID", "UserID")
            Dim query As String
            If editingSourceTable = "admin" Then
                query = "SELECT Lastname, Firstname, Role, Username, Password FROM admin WHERE AdminID = @uid"
            Else
                query = "SELECT Lastname, Firstname, Department, AssignedOffice, Role, Username, Password, Email, ContactNumber, StaffCode " &
                        "FROM users WHERE UserID = @uid"
            End If
            Using cmd As New MySqlCommand(query, cn)
                cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    If dr.Read() Then
                        txtLastname.Text = If(IsDBNull(dr("Lastname")), "", dr("Lastname").ToString())
                        txtFirstname.Text = If(IsDBNull(dr("Firstname")), "", dr("Firstname").ToString())

                        If editingSourceTable = "users" Then
                            If Not IsDBNull(dr("Department")) Then
                                cboDepartment.Text = dr("Department").ToString()
                            End If
                            If Not IsDBNull(dr("AssignedOffice")) Then
                                cboAssignedOffice.Text = dr("AssignedOffice").ToString()
                            End If
                            If Not IsDBNull(dr("Email")) AndAlso dr("Email").ToString() <> "N/A" Then
                                txtEmail.Text = dr("Email").ToString()
                            Else
                                txtEmail.Text = ""
                            End If
                            If Not IsDBNull(dr("ContactNumber")) AndAlso dr("ContactNumber").ToString() <> "N/A" Then
                                txtContactNo.Text = dr("ContactNumber").ToString()
                            Else
                                txtContactNo.Text = ""
                            End If
                            If Not IsDBNull(dr("StaffCode")) Then
                                lblStaffCode.Text = dr("StaffCode").ToString()
                            End If
                        End If
                        If Not IsDBNull(dr("Role")) Then
                            cboRole.Text = dr("Role").ToString().ToUpper()
                        End If
                        txtUsername.Text = If(IsDBNull(dr("Username")), "", dr("Username").ToString())
                        txtUsername.Tag = "ManualEdited"
                        txtPassword.Text = If(IsDBNull(dr("Password")), "", dr("Password").ToString())
                        txtConfirmPass.Text = txtPassword.Text
                    End If
                End Using
            End Using
        Catch ex As Exception
            MsgBox("Error loading User Data: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    ' ✅ NEW METHOD: Returns the user to the list panel after saving/updating
    Private Sub ReturnToManageUsers()
        Dim mainForm As frmMain = TryCast(Application.OpenForms("frmMain"), frmMain)
        If mainForm IsNot Nothing Then
            mainForm.Panel2.Controls.Clear()
            Dim frm As New frmManage_Users()
            frm.TopLevel = False
            frm.FormBorderStyle = FormBorderStyle.None
            frm.Dock = DockStyle.Fill
            mainForm.Panel2.Controls.Add(frm)
            frm.BringToFront()
            frm.Show()
        End If
    End Sub

    Private Sub frmcreateuser_KeyDown(sender As Object, e As KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True
            btnSubmit.PerformClick()
        End If
    End Sub

    Private Sub ConvertToUpperCase_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtLastname.KeyPress, txtFirstname.KeyPress
        If Not Char.IsLetter(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) AndAlso
           e.KeyChar <> " "c AndAlso e.KeyChar <> "ñ"c AndAlso e.KeyChar <> "Ñ"c Then
            e.Handled = True
            Return
        End If
        If Char.IsLower(e.KeyChar) Then
            e.KeyChar = Char.ToUpper(e.KeyChar)
        End If
    End Sub

    Private Sub txtContactNo_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtContactNo.KeyPress
        If Not Char.IsDigit(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) AndAlso e.KeyChar <> "-"c Then
            e.Handled = True
        End If
    End Sub

    Private Sub ClearAllValidationLabels()
        SetFeedbackLabel(lblLastnameError, "", False)
        SetFeedbackLabel(lblFirstnameError, "", False)
        SetFeedbackLabel(lblEmailError, "", False)
        SetFeedbackLabel(lblContactNoError, "", False)
        SetFeedbackLabel(lblUsernameError, "", False)
        SetFeedbackLabel(lblConfirmPassError, "", False)
        SetFeedbackLabel(lblRoleError, "", False)
        SetFeedbackLabel(lblAssignedOfficeError, "", False)
    End Sub

    Private Sub SetFeedbackLabel(lbl As Label, message As String, isError As Boolean)
        If lbl Is Nothing Then Exit Sub
        lbl.Text = message
        lbl.ForeColor = If(String.IsNullOrEmpty(message), Color.Black, If(isError, Color.Red, Color.Green))
    End Sub

    Private Function GetNextStaffCode() As String
        If editingUserID.HasValue Then Return lblStaffCode.Text
        Dim nextCode As String = "STF-001"
        Try
            connection()
            Dim sql = "SELECT StaffCode FROM users WHERE StaffCode LIKE 'STF-%' ORDER BY UserID DESC LIMIT 1"
            Using cmd As New MySqlCommand(sql, cn)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    If dr.Read() Then
                        Dim lastCode As String = dr("StaffCode").ToString()
                        If lastCode.Contains("-") Then
                            Dim parts = lastCode.Split("-"c)
                            If Integer.TryParse(parts(1), Nothing) Then
                                nextCode = "STF-" & (CInt(parts(1)) + 1).ToString("D3")
                            End If
                        End If
                    End If
                End Using
            End Using
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
        Return nextCode
    End Function

    Private Sub GenerateStaffCode()
        If Not editingUserID.HasValue Then
            lblStaffCode.Text = GetNextStaffCode()
        End If
    End Sub

    Private Sub cboRole_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboRole.SelectedIndexChanged
        If isFormLoading Then Exit Sub ' ✅ Prevent execution during load
        SetFeedbackLabel(lblRoleError, If(Not IsValidRole(cboRole.Text.Trim()), "Invalid role selected.", "✓ OK"), Not IsValidRole(cboRole.Text.Trim()))
        If Not editingUserID.HasValue Then UpdateUsernameSuggestion()
    End Sub

    Private Sub UpdateUsernameSuggestion() Handles txtFirstname.TextChanged, cboRole.SelectedIndexChanged
        If isFormLoading OrElse editingUserID.HasValue Then Exit Sub ' ✅ Prevent execution during load
        If txtUsername.Tag Is Nothing OrElse txtUsername.Tag.ToString() <> "AutoGenerated" Then Exit Sub
        If String.IsNullOrWhiteSpace(txtFirstname.Text) OrElse cboRole.SelectedIndex = -1 Then
            txtUsername.Clear()
            Exit Sub
        End If
        Dim cleanFirst = txtFirstname.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim cleanRole = cboRole.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim shortRole = If(cleanRole.Length >= 4, cleanRole.Substring(0, 4), cleanRole)
        Dim suggestedUser = $"{cleanFirst}{shortRole}"
        If suggestedUser.Contains("admin") Then suggestedUser &= "usr"
        Try
            connection()
            Dim counter = 1, checkUser = suggestedUser
            Do
                Using cmd As New MySqlCommand("SELECT Username FROM users WHERE LOWER(Username)=LOWER(@uname)", cn)
                    cmd.Parameters.AddWithValue("@uname", checkUser)
                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    Using dr = cmd.ExecuteReader()
                        If Not dr.HasRows Then Exit Do
                    End Using
                End Using
                checkUser = $"{suggestedUser}{counter}"
                counter += 1
            Loop
            txtUsername.Text = checkUser
            txtUsername.SelectionStart = txtUsername.TextLength
        Catch ex As Exception
            txtUsername.Text = suggestedUser
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtUsername.KeyPress
        txtUsername.Tag = "ManualEdited"
    End Sub

    Private Sub txtLastname_TextChanged(sender As Object, e As EventArgs) Handles txtLastname.TextChanged
        If isFormLoading Then Exit Sub ' ✅ Prevent execution during load
        If String.IsNullOrWhiteSpace(txtLastname.Text) Then
            SetFeedbackLabel(lblLastnameError, "Lastname is required.", True)
        ElseIf Not Regex.IsMatch(txtLastname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblLastnameError, "Letters only — no numbers or symbols.", True)
        Else
            SetFeedbackLabel(lblLastnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtFirstname_TextChanged(sender As Object, e As EventArgs) Handles txtFirstname.TextChanged
        If isFormLoading Then Exit Sub ' ✅ Prevent execution during load
        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            SetFeedbackLabel(lblFirstnameError, "Firstname is required.", True)
        ElseIf Not Regex.IsMatch(txtFirstname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblFirstnameError, "Letters only — no numbers or symbols.", True)
        Else
            SetFeedbackLabel(lblFirstnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub cboDepartment_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboDepartment.SelectedIndexChanged
        If isFormLoading OrElse (editingUserID.HasValue AndAlso editingSourceTable = "admin") Then Exit Sub ' ✅ Prevent execution during load
        SetFeedbackLabel(lblRoleError, If(cboDepartment.SelectedIndex = -1, "Department is required.", "✓ OK"), cboDepartment.SelectedIndex = -1)
    End Sub

    Private Sub cboAssignedOffice_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboAssignedOffice.SelectedIndexChanged
        If isFormLoading OrElse (editingUserID.HasValue AndAlso editingSourceTable = "admin") Then Exit Sub ' ✅ Prevent execution during load
        SetFeedbackLabel(lblAssignedOfficeError, If(cboAssignedOffice.SelectedIndex = -1, "Satellite Office is required.", "✓ OK"), cboAssignedOffice.SelectedIndex = -1)
    End Sub

    Private Sub txtEmail_TextChanged(sender As Object, e As EventArgs) Handles txtEmail.TextChanged
        If isFormLoading OrElse (editingUserID.HasValue AndAlso editingSourceTable = "admin") Then Exit Sub ' ✅ THIS STOPPED THE CRASH

        Dim val = txtEmail.Text.Trim().ToLower()
        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblEmailError, "Will be saved as N/A", False)
            Exit Sub
        End If
        If Not Regex.IsMatch(val, "^[a-zA-Z0-9._%+-]+@gmail\.com$", RegexOptions.IgnoreCase) Then
            SetFeedbackLabel(lblEmailError, "Must end with @gmail.com", True)
            Exit Sub
        End If
        Try
            connection()
            Dim checkSql As String
            If editingUserID.HasValue Then
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Email)=LOWER(@email) AND UserID<>@uid AND Email <> 'N/A'"
            Else
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Email)=LOWER(@email) AND Email <> 'N/A'"
            End If
            Using cmd As New MySqlCommand(checkSql, cn)
                cmd.Parameters.AddWithValue("@email", val)
                If editingUserID.HasValue Then cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                Dim exists = Convert.ToInt32(cmd.ExecuteScalar()) > 0
                SetFeedbackLabel(lblEmailError, If(exists, "Email already registered!", "✓ OK"), exists)
            End Using
        Catch ex As Exception
            SetFeedbackLabel(lblEmailError, "Error verifying email.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtContactNo_TextChanged(sender As Object, e As EventArgs) Handles txtContactNo.TextChanged
        If isFormLoading OrElse (editingUserID.HasValue AndAlso editingSourceTable = "admin") Then Exit Sub ' ✅ Prevent execution during load
        Dim val = txtContactNo.Text.Trim()
        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblContactNoError, "Will be saved as N/A", False)
            Exit Sub
        End If
        If Not Regex.IsMatch(val, "^[0-9-]+$") Then
            SetFeedbackLabel(lblContactNoError, "Numbers and hyphen only.", True)
            Exit Sub
        End If
        Try
            connection()
            Dim checkSql As String
            If editingUserID.HasValue Then
                checkSql = "SELECT COUNT(*) FROM users WHERE ContactNumber=@contact AND UserID<>@uid AND ContactNumber <> 'N/A'"
            Else
                checkSql = "SELECT COUNT(*) FROM users WHERE ContactNumber=@contact AND ContactNumber <> 'N/A'"
            End If
            Using cmd As New MySqlCommand(checkSql, cn)
                cmd.Parameters.AddWithValue("@contact", val)
                If editingUserID.HasValue Then cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                Dim exists = Convert.ToInt32(cmd.ExecuteScalar()) > 0
                SetFeedbackLabel(lblContactNoError, If(exists, "⚠️ Contact Number already registered!", "✓ OK"), exists)
            End Using
        Catch ex As Exception
            SetFeedbackLabel(lblContactNoError, "Error verifying contact.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_TextChanged(sender As Object, e As EventArgs) Handles txtUsername.TextChanged
        If isFormLoading Then Exit Sub ' ✅ Prevent execution during load
        Dim val = txtUsername.Text.Trim()
        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblUsernameError, "Username is required.", True)
            Exit Sub
        End If
        If val.ToLower().Contains("admin") Then
            SetFeedbackLabel(lblUsernameError, "Username with 'admin' is prohibited.", True)
            Exit Sub
        End If
        Try
            connection()
            Dim checkSql As String
            If editingUserID.HasValue Then
                checkSql = If(editingSourceTable = "admin",
                    "SELECT COUNT(*) FROM admin WHERE LOWER(Username)=LOWER(@uname) AND AdminID<>@uid",
                    "SELECT COUNT(*) FROM users WHERE LOWER(Username)=LOWER(@uname) AND UserID<>@uid")
            Else
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Username)=LOWER(@uname)"
            End If
            Using cmd As New MySqlCommand(checkSql, cn)
                cmd.Parameters.AddWithValue("@uname", val)
                If editingUserID.HasValue Then cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                Dim exists = Convert.ToInt32(cmd.ExecuteScalar()) > 0
                SetFeedbackLabel(lblUsernameError, If(exists, "⚠️ Username already taken!", "✓ OK"), exists)
            End Using
        Catch ex As Exception
            SetFeedbackLabel(lblUsernameError, "Error verifying username.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtPassword_TextChanged(sender As Object, e As EventArgs) Handles txtPassword.TextChanged, txtConfirmPass.TextChanged
        If isFormLoading Then Exit Sub ' ✅ Prevent execution during load
        Dim hasUpper = txtPassword.Text.Any(AddressOf Char.IsUpper)
        Dim hasLower = txtPassword.Text.Any(AddressOf Char.IsLower)
        If String.IsNullOrWhiteSpace(txtPassword.Text) Then
            SetFeedbackLabel(lblConfirmPassError, "Password is required.", True)
        ElseIf Not hasUpper OrElse Not hasLower OrElse txtPassword.Text.Length < 6 Then
            SetFeedbackLabel(lblConfirmPassError, "Min 6 chars — uppercase & lowercase.", True)
        ElseIf txtPassword.Text.Trim() <> txtConfirmPass.Text.Trim() Then
            SetFeedbackLabel(lblConfirmPassError, "Passwords do not match.", True)
        Else
            SetFeedbackLabel(lblConfirmPassError, "✓ Passwords Match", False)
        End If
    End Sub

    Private Sub btnSubmit_Click(sender As Object, e As EventArgs) Handles btnSubmit.Click
        If Not IsValidRole(cboRole.Text.Trim()) Then
            MsgBox("Selected role is invalid!", MsgBoxStyle.Exclamation)
            Return
        End If

        If editingSourceTable = "users" AndAlso Not editingUserID.HasValue Then
            If cboDepartment.SelectedIndex = -1 Then
                MsgBox("Please select a Department!", MsgBoxStyle.Exclamation)
                Return
            End If
            If cboAssignedOffice.SelectedIndex = -1 Then
                MsgBox("Please select a Satellite Office!", MsgBoxStyle.Exclamation)
                Return
            End If
        End If

        Dim hasError As Boolean = False
        If lblLastnameError.ForeColor = Color.Red Then hasError = True
        If lblFirstnameError.ForeColor = Color.Red Then hasError = True
        If lblConfirmPassError.ForeColor = Color.Red Then hasError = True
        If lblUsernameError.ForeColor = Color.Red Then hasError = True
        If editingSourceTable = "users" Then
            If lblEmailError.ForeColor = Color.Red AndAlso Not String.IsNullOrWhiteSpace(txtEmail.Text.Trim()) Then hasError = True
            If lblContactNoError.ForeColor = Color.Red AndAlso Not String.IsNullOrWhiteSpace(txtContactNo.Text.Trim()) Then hasError = True
            If lblRoleError.ForeColor = Color.Red Then hasError = True
            If lblAssignedOfficeError.ForeColor = Color.Red Then hasError = True
        End If

        If hasError Then
            MsgBox("Please fix all errors before submitting!", MsgBoxStyle.Exclamation)
            Return
        End If

        Dim fullName As String = $"{txtFirstname.Text.Trim()} {txtLastname.Text.Trim()}"
        If editingUserID.HasValue Then
            If MsgBox($"Are you sure you want to UPDATE user ""{fullName}""?",
                      MsgBoxStyle.YesNo + MsgBoxStyle.Question, "Confirm Update") = MsgBoxResult.No Then
                Return
            End If
        Else
            If MsgBox($"Are you sure you want to ADD NEW USER ""{fullName}""?",
                      MsgBoxStyle.YesNo + MsgBoxStyle.Question, "Confirm Save") = MsgBoxResult.No Then
                Return
            End If
        End If

        Try
            connection()
            Dim emailVal = If(String.IsNullOrWhiteSpace(txtEmail.Text.Trim()), "N/A", txtEmail.Text.Trim().ToLower())
            Dim contactVal = If(String.IsNullOrWhiteSpace(txtContactNo.Text.Trim()), "N/A", txtContactNo.Text.Trim())

            If editingUserID.HasValue Then
                Dim idCol = If(editingSourceTable = "admin", "AdminID", "UserID")
                Dim sql As String
                If editingSourceTable = "admin" Then
                    sql = "UPDATE admin SET Lastname=@lname, Firstname=@fname, Role=@role, Username=@uname, Password=@pass " &
                          "WHERE " & idCol & "=@uid"
                Else
                    sql = "UPDATE users SET Lastname=@lname, Firstname=@fname, Department=@dept, AssignedOffice=@office, " &
                          "Role=@role, Username=@uname, Password=@pass, Email=@email, ContactNumber=@contact " &
                          "WHERE " & idCol & "=@uid"
                End If
                Using cmd As New MySqlCommand(sql, cn)
                    cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@role", cboRole.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
                    cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
                    If editingSourceTable = "users" Then
                        cmd.Parameters.AddWithValue("@dept", cboDepartment.Text.Trim())
                        cmd.Parameters.AddWithValue("@office", If(cboAssignedOffice.SelectedIndex >= 0, cboAssignedOffice.Text.Trim(), DBNull.Value))
                        cmd.Parameters.AddWithValue("@email", emailVal)
                        cmd.Parameters.AddWithValue("@contact", contactVal)
                    End If
                    cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    cmd.ExecuteNonQuery()
                End Using
                MsgBox("User updated successfully!", MsgBoxStyle.Information)
                ReturnToManageUsers() ' ✅ Returns directly to the grid
            Else
                Dim freshStaffCode = GetNextStaffCode()
                Dim assignedOfficeText As String = If(cboAssignedOffice.SelectedIndex >= 0, cboAssignedOffice.Text.Trim(), "")
                Dim sql = "INSERT INTO users (StaffCode, Username, Password, Lastname, Firstname, Department, " &
                          "AssignedOffice, Role, Email, ContactNumber, AccountStatus, LoginAttempts) " &
                          "VALUES (@scode, @uname, @pass, @lname, @fname, @dept, @office, @role, @email, @contact, 'Active', 0)"
                Using cmd As New MySqlCommand(sql, cn)
                    cmd.Parameters.AddWithValue("@scode", freshStaffCode)
                    cmd.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
                    cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
                    cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@dept", cboDepartment.Text.Trim())
                    cmd.Parameters.AddWithValue("@office", assignedOfficeText)
                    cmd.Parameters.AddWithValue("@role", cboRole.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@email", emailVal)
                    cmd.Parameters.AddWithValue("@contact", contactVal)
                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    cmd.ExecuteNonQuery()
                End Using
                MsgBox("Successfully Registered New User!", MsgBoxStyle.Information)
                ReturnToManageUsers() ' ✅ Returns directly to the grid
            End If
        Catch ex As MySqlException
            Dim errMsg As String = "Database Error: " & ex.Message
            If ex.Number = 1062 Then
                errMsg = "DUPLICATE FOUND!" & vbCrLf &
                         "— Username already exists" & vbCrLf &
                         "— Email already registered" & vbCrLf &
                         "— Contact Number already registered" & vbCrLf &
                         "Please use different values."
            End If
            MsgBox(errMsg, MsgBoxStyle.Critical)
        Catch ex As Exception
            MsgBox("Error: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub btnClearAll_Click(sender As Object, e As EventArgs) Handles btnClearAll.Click
        If editingUserID.HasValue Then
            If MsgBox("Clear all changes and reset to original values?",
                      MsgBoxStyle.YesNo + MsgBoxStyle.Question, "Confirm Clear") = MsgBoxResult.No Then
                Return
            End If
            LoadUserDataForEdit()
            ClearAllValidationLabels()
        Else
            If MsgBox("Cancel creation and go back?",
                      MsgBoxStyle.YesNo + MsgBoxStyle.Question, "Confirm Cancel") = MsgBoxResult.No Then
                Return
            End If
            ReturnToManageUsers() ' ✅ The back/clear button now correctly exits out of the form
        End If
    End Sub

    Private Sub ClearForm()
        txtLastname.Clear()
        txtFirstname.Clear()
        txtEmail.Clear()
        txtContactNo.Clear()
        txtUsername.Clear()
        txtUsername.Tag = "AutoGenerated"
        txtPassword.Clear()
        txtConfirmPass.Clear()
        cboRole.SelectedIndex = -1
        cboDepartment.SelectedIndex = -1
        cboAssignedOffice.SelectedIndex = -1
        ClearAllValidationLabels()
    End Sub

    Private Sub frmcreateuser_FormClosing(sender As Object, e As FormClosingEventArgs) Handles MyBase.FormClosing
        Dim mainForm As frmMain = TryCast(Application.OpenForms("frmMain"), frmMain)
        If mainForm IsNot Nothing Then
            mainForm.Enabled = True
            mainForm.Activate()
        End If
    End Sub
End Class