Imports MySql.Data.MySqlClient
Imports System.IO
Imports System.Drawing.Imaging
Imports System.Text.RegularExpressions

Public Class frmcreateuser
    Private profileImageBytes As Byte() = Nothing
    Private editingUserID As Integer? = Nothing ' Nothing = create mode, may value = edit mode
    Private editingSourceTable As String = "users"

    ' ✅ Constructor — para sa pag-edit
    Public Sub New(ByVal userID As Integer, Optional ByVal srcTable As String = "users")
        InitializeComponent()
        editingUserID = userID
        editingSourceTable = srcTable
    End Sub

    ' ✅ Default constructor — para sa paglikha ng bago
    Public Sub New()
        InitializeComponent()
    End Sub

    Private Sub frmcreateuser_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.TopMost = True
        Me.KeyPreview = True
        frmMain.Enabled = False

        ' ✅ Itago ang Department at Email kung ADMIN ang ine-edit
        If editingUserID.HasValue AndAlso editingSourceTable = "admin" Then
            cboDepartment.Visible = False
            lblDepartmentError.Visible = False
            txtEmail.Visible = False
            lblEmailError.Visible = False
        Else
            cboDepartment.Visible = True
            lblDepartmentError.Visible = True
            txtEmail.Visible = True
            lblEmailError.Visible = True
            LoadDepartmentsCombo()
        End If

        LoadRolesFromDatabase()

        If editingUserID.HasValue Then
            ' ✅ EDIT MODE — I-load ang datos
            LoadUserDataForEdit()
            btnSubmit.Text = "Update User"
            Me.Text = "Edit User Information"
        Else
            ' ✅ CREATE MODE — bagong user
            txtUsername.Tag = "AutoGenerated"
            GenerateStaffCode()
            Me.Text = "Create New User"
        End If

        ClearAllValidationLabels()
    End Sub

    Private Sub LoadDepartmentsCombo()
        Try
            connection()
            Dim sql = "SELECT DepartmentName FROM departments WHERE IsActive = 1 ORDER BY DepartmentName ASC"
            Dim dtDept As New DataTable()
            Using localCmd As New MySqlCommand(sql, cn)
                Using adapter As New MySqlDataAdapter(localCmd)
                    adapter.Fill(dtDept)
                End Using
            End Using
            If cboDepartment IsNot Nothing Then
                cboDepartment.DataSource = dtDept
                cboDepartment.DisplayMember = "DepartmentName"
                cboDepartment.ValueMember = "DepartmentName"
                cboDepartment.SelectedIndex = -1
            End If
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
    End Sub

    ' ✅ Dynamic roles mula sa DB
    Private Sub LoadRolesFromDatabase()
        If cboRole Is Nothing Then Exit Sub
        cboRole.Items.Clear()
        Try
            connection()
            Dim sql = "SELECT RoleName FROM user_roles ORDER BY RoleName ASC"
            Using cmd As New MySqlCommand(sql, cn)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    While dr.Read()
                        cboRole.Items.Add(dr("RoleName").ToString().ToUpper())
                    End While
                End Using
            End Using
        Catch ex As Exception
            MsgBox("Error loading roles: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Function IsValidRole(roleName As String) As Boolean
        If String.IsNullOrWhiteSpace(roleName) Then Return False
        Try
            connection()
            Dim sql = "SELECT COUNT(*) FROM user_roles WHERE UPPER(RoleName) = UPPER(@rname)"
            Using cmd As New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@rname", roleName.Trim())
                Return Convert.ToInt32(cmd.ExecuteScalar()) > 0
            End Using
        Catch ex As Exception
            Return False
        Finally
            CloseConnection()
        End Try
    End Function

    ' ✅ I-load ang datos kapag nag-e-edit — WALANG Department sa admin
    Private Sub LoadUserDataForEdit()
        Try
            connection()
            Dim idCol As String = If(editingSourceTable = "admin", "AdminID", "UserID")
            Dim query As String

            If editingSourceTable = "admin" Then
                ' ✅ ADMIN — WALANG Department, walang Email, walang StaffCode
                query = "SELECT Lastname, Firstname, Role, Username, Password, Picture FROM admin WHERE AdminID = @uid"
            Else
                ' ✅ USERS — kumpleto
                query = "SELECT Lastname, Firstname, Department, Role, Username, Password, Email, StaffCode, Picture FROM users WHERE UserID = @uid"
            End If

            Using cmd As New MySqlCommand(query, cn)
                cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    If dr.Read() Then
                        txtLastname.Text = If(dr("Lastname") Is DBNull.Value, "", dr("Lastname").ToString())
                        txtFirstname.Text = If(dr("Firstname") Is DBNull.Value, "", dr("Firstname").ToString())

                        ' ✅ Department — USERS lang
                        If editingSourceTable = "users" AndAlso Not dr("Department") Is DBNull.Value Then
                            cboDepartment.Text = dr("Department").ToString()
                        End If

                        If Not dr("Role") Is DBNull.Value Then
                            cboRole.Text = dr("Role").ToString().ToUpper()
                        End If

                        txtUsername.Text = If(dr("Username") Is DBNull.Value, "", dr("Username").ToString())
                        txtUsername.Tag = "ManualEdited"

                        txtPassword.Text = If(dr("Password") Is DBNull.Value, "", dr("Password").ToString())
                        txtConfirmPass.Text = txtPassword.Text

                        ' ✅ Email — USERS lang
                        If editingSourceTable = "users" AndAlso Not dr("Email") Is DBNull.Value Then
                            txtEmail.Text = dr("Email").ToString()
                        End If

                        ' ✅ StaffCode — USERS lang
                        If editingSourceTable = "users" AndAlso Not dr("StaffCode") Is DBNull.Value Then
                            lblStaffCode.Text = dr("StaffCode").ToString()
                        End If

                        ' Litrato — pareho
                        If Not dr("Picture") Is DBNull.Value Then
                            profileImageBytes = CType(dr("Picture"), Byte())
                            Using ms As New MemoryStream(profileImageBytes)
                                picUser.SizeMode = PictureBoxSizeMode.StretchImage
                                picUser.Image = Image.FromStream(ms)
                            End Using
                            SetFeedbackLabel(lblPictureError, "✓ Loaded", False)
                        End If
                    End If
                End Using
            End Using
        Catch ex As Exception
            MsgBox("Error loading user data: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub frmcreateuser_KeyDown(sender As Object, e As KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True
            btnSubmit.PerformClick()
        End If
    End Sub

    Private Sub ConvertToUpperCase_KeyPress(sender As Object, e As KeyPressEventArgs) Handles _
        txtLastname.KeyPress, txtFirstname.KeyPress
        If Char.IsLower(e.KeyChar) Then
            e.KeyChar = Char.ToUpper(e.KeyChar)
        End If
    End Sub

    Private Sub ClearAllValidationLabels()
        SetFeedbackLabel(lblLastnameError, "", False)
        SetFeedbackLabel(lblFirstnameError, "", False)
        SetFeedbackLabel(lblEmailError, "", False)
        SetFeedbackLabel(lblUsernameError, "", False)
        SetFeedbackLabel(lblConfirmPassError, "", False)
        SetFeedbackLabel(lblPictureError, "", False)
        SetFeedbackLabel(lblDepartmentError, "", False)
        SetFeedbackLabel(lblRoleError, "", False)
    End Sub

    Private Sub SetFeedbackLabel(lbl As Label, message As String, isError As Boolean)
        If lbl Is Nothing Then Exit Sub
        lbl.Text = message
        lbl.ForeColor = If(String.IsNullOrEmpty(message), Color.Black, If(isError, Color.Red, Color.Green))
    End Sub

    Private Function GetNextStaffCode() As String
        If editingUserID.HasValue Then Return lblStaffCode.Text
        Dim nextCode As String = "STF-001"
        Try
            connection()
            Dim sql = "SELECT StaffCode FROM users WHERE StaffCode LIKE 'STF-%' ORDER BY UserID DESC LIMIT 1"
            Using cmd As New MySqlCommand(sql, cn)
                If cn.State = ConnectionState.Open Then cn.Close()
                cn.Open()
                Using dr As MySqlDataReader = cmd.ExecuteReader()
                    If dr.Read() Then
                        Dim lastCode As String = dr("StaffCode").ToString()
                        If lastCode.Contains("-") Then
                            Dim parts = lastCode.Split("-"c)
                            If Integer.TryParse(parts(1), Nothing) Then
                                nextCode = "STF-" & (CInt(parts(1)) + 1).ToString("D3")
                            End If
                        End If
                    End If
                End Using
            End Using
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
        Return nextCode
    End Function

    Private Sub GenerateStaffCode()
        If Not editingUserID.HasValue Then
            lblStaffCode.Text = GetNextStaffCode()
        End If
    End Sub

    Private Sub cboRole_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboRole.SelectedIndexChanged
        SetFeedbackLabel(lblRoleError, If(Not IsValidRole(cboRole.Text.Trim()), "Invalid role selected.", "✓ OK"), Not IsValidRole(cboRole.Text.Trim()))
        If Not editingUserID.HasValue Then UpdateUsernameSuggestion()
    End Sub

    Private Sub UpdateUsernameSuggestion() Handles txtFirstname.TextChanged, cboRole.SelectedIndexChanged
        If editingUserID.HasValue Then Exit Sub
        If txtUsername.Tag Is Nothing OrElse txtUsername.Tag.ToString() <> "AutoGenerated" Then Exit Sub
        If String.IsNullOrWhiteSpace(txtFirstname.Text) OrElse cboRole.SelectedIndex = -1 Then
            txtUsername.Clear()
            Exit Sub
        End If
        Dim cleanFirst = txtFirstname.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim cleanRole = cboRole.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim shortRole = If(cleanRole.Length >= 4, cleanRole.Substring(0, 4), cleanRole)
        Dim suggestedUser = $"{cleanFirst}{shortRole}"
        If suggestedUser.Contains("admin") Then suggestedUser &= "usr"
        Try
            connection()
            Dim counter = 1, checkUser = suggestedUser
            Do
                Using cmd As New MySqlCommand("SELECT Username FROM users WHERE LOWER(Username)=LOWER(@uname)", cn)
                    cmd.Parameters.AddWithValue("@uname", checkUser)
                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    Using dr = cmd.ExecuteReader()
                        If Not dr.HasRows Then Exit Do
                    End Using
                End Using
                checkUser = $"{suggestedUser}{counter}"
                counter += 1
            Loop
            txtUsername.Text = checkUser
            txtUsername.SelectionStart = txtUsername.TextLength
        Catch ex As Exception
            txtUsername.Text = suggestedUser
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtUsername.KeyPress
        txtUsername.Tag = "ManualEdited"
    End Sub

    Private Sub txtLastname_TextChanged(sender As Object, e As EventArgs) Handles txtLastname.TextChanged
        If String.IsNullOrWhiteSpace(txtLastname.Text) Then
            SetFeedbackLabel(lblLastnameError, "Lastname is required.", True)
        ElseIf Not Regex.IsMatch(txtLastname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblLastnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblLastnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtFirstname_TextChanged(sender As Object, e As EventArgs) Handles txtFirstname.TextChanged
        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            SetFeedbackLabel(lblFirstnameError, "Firstname is required.", True)
        ElseIf Not Regex.IsMatch(txtFirstname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblFirstnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblFirstnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub cboDepartment_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboDepartment.SelectedIndexChanged
        ' ✅ I-skip kung Admin — hindi nakikita naman
        If editingUserID.HasValue AndAlso editingSourceTable = "admin" Then Exit Sub
        SetFeedbackLabel(lblDepartmentError, If(cboDepartment.SelectedIndex = -1, "Department is required.", "✓ OK"), cboDepartment.SelectedIndex = -1)
    End Sub

    Private Sub txtEmail_TextChanged(sender As Object, e As EventArgs) Handles txtEmail.TextChanged
        ' ✅ I-skip kung Admin
        If editingUserID.HasValue AndAlso editingSourceTable = "admin" Then Exit Sub

        Dim val = txtEmail.Text.Trim().ToLower()
        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblEmailError, "Email is required.", True)
            Exit Sub
        End If
        If Not Regex.IsMatch(val, "^[a-zA-Z0-9._%+-]+@gmail\.com$", RegexOptions.IgnoreCase) Then
            SetFeedbackLabel(lblEmailError, "Must end strictly with @gmail.com.", True)
            Exit Sub
        End If
        Try
            connection()
            Dim checkSql As String
            If editingUserID.HasValue Then
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Email)=LOWER(@email) AND UserID<>@uid"
            Else
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Email)=LOWER(@email)"
            End If
            Using cmd As New MySqlCommand(checkSql, cn)
                cmd.Parameters.AddWithValue("@email", val)
                If editingUserID.HasValue Then cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                SetFeedbackLabel(lblEmailError, If(CInt(cmd.ExecuteScalar()) > 0, "Email already registered!", "✓ OK"), CInt(cmd.ExecuteScalar()) > 0)
            End Using
        Catch ex As Exception
            SetFeedbackLabel(lblEmailError, "Error verifying email.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_TextChanged(sender As Object, e As EventArgs) Handles txtUsername.TextChanged
        Dim val = txtUsername.Text.Trim()
        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblUsernameError, "Username is required.", True)
            Exit Sub
        End If
        If val.ToLower().Contains("admin") Then
            SetFeedbackLabel(lblUsernameError, "Usernames related to 'admin' are prohibited.", True)
            Exit Sub
        End If
        Try
            connection()
            Dim checkSql As String
            If editingUserID.HasValue Then
                checkSql = If(editingSourceTable = "admin",
                    "SELECT COUNT(*) FROM admin WHERE LOWER(Username)=LOWER(@uname) AND AdminID<>@uid",
                    "SELECT COUNT(*) FROM users WHERE LOWER(Username)=LOWER(@uname) AND UserID<>@uid")
            Else
                checkSql = "SELECT COUNT(*) FROM users WHERE LOWER(Username)=LOWER(@uname)"
            End If
            Using cmd As New MySqlCommand(checkSql, cn)
                cmd.Parameters.AddWithValue("@uname", val)
                If editingUserID.HasValue Then cmd.Parameters.AddWithValue("@uid", editingUserID.Value)
                SetFeedbackLabel(lblUsernameError, If(CInt(cmd.ExecuteScalar()) > 0, "Username already taken!", "✓ OK"), CInt(cmd.ExecuteScalar()) > 0)
            End Using
        Catch ex As Exception
            SetFeedbackLabel(lblUsernameError, "Error verifying username.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtPassword_TextChanged(sender As Object, e As EventArgs) Handles txtPassword.TextChanged, txtConfirmPass.TextChanged
        Dim hasUpper = txtPassword.Text.Any(AddressOf Char.IsUpper)
        Dim hasLower = txtPassword.Text.Any(AddressOf Char.IsLower)
        If String.IsNullOrWhiteSpace(txtPassword.Text) Then
            SetFeedbackLabel(lblConfirmPassError, "Password is required.", True)
        ElseIf Not hasUpper OrElse Not hasLower OrElse txtPassword.Text.Length < 6 Then
            SetFeedbackLabel(lblConfirmPassError, "Min 6 chars, uppercase & lowercase.", True)
        ElseIf txtPassword.Text.Trim() <> txtConfirmPass.Text.Trim() Then
            SetFeedbackLabel(lblConfirmPassError, "Passwords do not match.", True)
        Else
            SetFeedbackLabel(lblConfirmPassError, "✓ Passwords Match", False)
        End If
    End Sub

    Private Sub picUser_DoubleClick(sender As Object, e As EventArgs) Handles picUser.DoubleClick
        Using ofd As New OpenFileDialog()
            ofd.Filter = "Image Files (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png"
            If ofd.ShowDialog() = DialogResult.OK Then
                picUser.SizeMode = PictureBoxSizeMode.StretchImage
                If picUser.Image IsNot Nothing Then picUser.Image.Dispose()
                picUser.Image = Image.FromFile(ofd.FileName)
                Using ms As New MemoryStream()
                    picUser.Image.Save(ms, Imaging.ImageFormat.Jpeg)
                    profileImageBytes = ms.ToArray()
                End Using
                SetFeedbackLabel(lblPictureError, "✓ Uploaded", False)
            End If
        End Using
    End Sub

    Private Sub btnSubmit_Click(sender As Object, e As EventArgs) Handles btnSubmit.Click
        ' Role validation
        If Not IsValidRole(cboRole.Text.Trim()) Then
            MsgBox("Selected role is invalid!", MsgBoxStyle.Exclamation)
            Return
        End If

        ' ✅ Department validation — USERS lang
        If editingSourceTable = "users" AndAlso Not editingUserID.HasValue Then
            If cboDepartment.SelectedIndex = -1 Then
                MsgBox("Please select a department!", MsgBoxStyle.Exclamation)
                Return
            End If
        End If

        ' All validation check
        Dim hasError As Boolean = False
        If lblLastnameError.ForeColor = Color.Red Then hasError = True
        If lblFirstnameError.ForeColor = Color.Red Then hasError = True
        If lblConfirmPassError.ForeColor = Color.Red Then hasError = True
        If editingSourceTable = "users" Then
            If lblEmailError.ForeColor = Color.Red Then hasError = True
            If lblDepartmentError.ForeColor = Color.Red Then hasError = True
        End If
        If lblUsernameError.ForeColor = Color.Red Then hasError = True

        If hasError Then
            MsgBox("Please resolve all validation errors before submitting!", MsgBoxStyle.Exclamation)
            Return
        End If

        Try
            connection()
            If editingUserID.HasValue Then
                ' ✅ UPDATE MODE
                If MsgBox("Update this user information?", MsgBoxStyle.YesNo + MsgBoxStyle.Question) = MsgBoxResult.No Then Return
                Dim idCol = If(editingSourceTable = "admin", "AdminID", "UserID")
                Dim sql As String

                If editingSourceTable = "admin" Then
                    ' ✅ ADMIN — walang Department, walang Email
                    sql = "UPDATE admin SET Lastname=@lname, Firstname=@fname, Role=@role, Username=@uname, Password=@pass, Picture=@pic WHERE " & idCol & "=@uid"
                Else
                    ' ✅ USERS — kumpleto
                    sql = "UPDATE users SET Lastname=@lname, Firstname=@fname, Department=@dept, Role=@role, Username=@uname, Password=@pass, Email=@email, Picture=@pic WHERE " & idCol & "=@uid"
                End If

                Using cmd As New MySqlCommand(sql, cn)
                    cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
                    If editingSourceTable = "users" Then
                        cmd.Parameters.AddWithValue("@dept", cboDepartment.Text.Trim())
                        cmd.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())
                    End If
                    cmd.Parameters.AddWithValue("@role", cboRole.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
                    cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
                    cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = If(profileImageBytes IsNot Nothing, profileImageBytes, DBNull.Value)
                    cmd.Parameters.AddWithValue("@uid", editingUserID.Value)

                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    cmd.ExecuteNonQuery()
                End Using

                MsgBox("User updated successfully!", MsgBoxStyle.Information)
                Me.DialogResult = DialogResult.OK
                Me.Close()
            Else
                ' ✅ INSERT MODE — para sa bagong USER
                Dim freshStaffCode = GetNextStaffCode()
                Dim sql = "INSERT INTO users (StaffCode, Username, Password, Lastname, Firstname, Department, Role, Email, Picture, AccountStatus, LoginAttempts) " &
                           "VALUES (@scode, @uname, @pass, @lname, @fname, @dept, @role, @email, @pic, 'Active', 0)"
                Using cmd As New MySqlCommand(sql, cn)
                    cmd.Parameters.AddWithValue("@scode", freshStaffCode)
                    cmd.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
                    cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
                    cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@dept", cboDepartment.Text.Trim())
                    cmd.Parameters.AddWithValue("@role", cboRole.Text.Trim().ToUpper())
                    cmd.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())
                    cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = If(profileImageBytes IsNot Nothing, profileImageBytes, DBNull.Value)

                    If cn.State = ConnectionState.Open Then cn.Close()
                    cn.Open()
                    cmd.ExecuteNonQuery()
                End Using

                MsgBox("Successfully Registered New User!", MsgBoxStyle.Information)
                ClearForm()
                GenerateStaffCode()
            End If
        Catch ex As MySqlException
            MsgBox(If(ex.Number = 1062, "Duplicate entry: Username or Email already exists!", "Database Error: " & ex.Message), MsgBoxStyle.Critical)
        Catch ex As Exception
            MsgBox("Error: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub ClearForm()
        txtLastname.Clear()
        txtFirstname.Clear()
        txtEmail.Clear()
        txtUsername.Clear()
        txtUsername.Tag = "AutoGenerated"
        txtPassword.Clear()
        txtConfirmPass.Clear()
        If cboRole.Items.Count > 0 Then cboRole.SelectedIndex = 0
        cboDepartment.SelectedIndex = -1
        picUser.Image = Nothing
        profileImageBytes = Nothing
        ClearAllValidationLabels()
    End Sub

    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        If MsgBox("Are you sure you want to Cancel?", MsgBoxStyle.YesNo + MsgBoxStyle.Question) = MsgBoxResult.No Then Return
        ClearForm()
        Me.Close()
    End Sub

    Private Sub frmcreateuser_FormClosing(sender As Object, e As FormClosingEventArgs) Handles MyBase.FormClosing
        Dim mainForm As frmMain = TryCast(Application.OpenForms("frmMain"), frmMain)
        If mainForm IsNot Nothing Then
            mainForm.Enabled = True
            mainForm.Activate()
        End If
    End Sub
End Class