Imports MySql.Data.MySqlClient
Imports System.IO
Imports System.Drawing.Imaging
Imports System.Text.RegularExpressions

Public Class frmcreateuser

    Private profileImageBytes As Byte() = Nothing

    Private Sub frmcreateuser_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.TopMost = True
        Me.KeyPreview = True
        frmMain.Enabled = False

        LoadDepartmentsCombo()
        LoadRolesCombo()

        txtUsername.Tag = "AutoGenerated"
        GenerateStaffCode()
        ClearAllValidationLabels()
    End Sub

    Private Sub LoadDepartmentsCombo()
        Try
            connection()
            sql = "SELECT DepartmentName FROM departments WHERE IsActive = 1 ORDER BY DepartmentName ASC"
            Dim dtDept As New DataTable()
            Using localCmd As New MySqlCommand(sql, cn)
                Using adapter As New MySqlDataAdapter(localCmd)
                    adapter.Fill(dtDept)
                End Using
            End Using

            If cboDepartment IsNot Nothing Then
                cboDepartment.DataSource = dtDept
                cboDepartment.DisplayMember = "DepartmentName"
                cboDepartment.ValueMember = "DepartmentName"
                cboDepartment.SelectedIndex = -1
            End If
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub LoadRolesCombo()
        If cboRole Is Nothing Then Exit Sub
        cboRole.Items.Clear()
        cboRole.Items.AddRange({
            "ADMINISTRATOR", "SYSTEM ADMIN", "MANAGER", "SUPERVISOR",
            "STAFF", "OFFICE STAFF", "ENCODER", "CLERK",
            "SECURITY", "SECURITY GUARD", "RECEPTIONIST",
            "CASHIER", "ACCOUNTING", "AUDITOR", "HR STAFF",
            "IT SUPPORT", "TECHNICIAN", "MAINTENANCE",
            "DRIVER", "INVENTORY STAFF", "NURSE", "MEDICAL STAFF"
        })
        If cboRole.Items.Count > 0 Then cboRole.SelectedIndex = 0
    End Sub

    Private Sub frmcreateuser_KeyDown(sender As Object, e As KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True
            btnSubmit.PerformClick()
        End If
    End Sub

    Private Sub ConvertToUpperCase_KeyPress(sender As Object, e As KeyPressEventArgs) Handles _
        txtLastname.KeyPress, txtFirstname.KeyPress

        If Char.IsLower(e.KeyChar) Then
            e.KeyChar = Char.ToUpper(e.KeyChar)
        End If
    End Sub

    Private Sub ClearAllValidationLabels()
        SetFeedbackLabel(lblLastnameError, "", False)
        SetFeedbackLabel(lblFirstnameError, "", False)
        SetFeedbackLabel(lblEmailError, "", False)
        SetFeedbackLabel(lblUsernameError, "", False)
        SetFeedbackLabel(lblConfirmPassError, "", False)
        SetFeedbackLabel(lblPictureError, "", False)
        SetFeedbackLabel(lblDepartmentError, "", False)
    End Sub

    Private Sub SetFeedbackLabel(lbl As Label, message As String, isError As Boolean)
        If lbl Is Nothing Then Exit Sub
        lbl.Text = message
        If String.IsNullOrEmpty(message) Then
            lbl.ForeColor = Color.Black
        ElseIf isError Then
            lbl.ForeColor = Color.Red
        Else
            lbl.ForeColor = Color.Green
        End If
    End Sub

    Private Function GetNextStaffCode() As String
        Dim nextCode As String = "STF-001"
        Try
            connection()
            sql = "SELECT StaffCode FROM users WHERE StaffCode LIKE 'STF-%' ORDER BY UserID DESC LIMIT 1"
            cmd = New MySqlCommand(sql, cn)
            dr = cmd.ExecuteReader()

            If dr.Read() Then
                Dim lastCode As String = dr("StaffCode").ToString()
                If lastCode.Contains("-") Then
                    Dim parts() As String = lastCode.Split("-"c)
                    Dim numericPart As Integer
                    If Integer.TryParse(parts(1), numericPart) Then
                        nextCode = "STF-" & (numericPart + 1).ToString("D3")
                    End If
                End If
            End If
            dr.Close()
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
        Return nextCode
    End Function

    Private Sub GenerateStaffCode()
        Dim code As String = GetNextStaffCode()
        If lblStaffCode IsNot Nothing Then
            lblStaffCode.Text = code
        End If
    End Sub

    Private Sub UpdateUsernameSuggestion() Handles txtFirstname.TextChanged, cboRole.SelectedIndexChanged
        If txtUsername.Tag Is Nothing OrElse txtUsername.Tag.ToString() <> "AutoGenerated" Then Exit Sub

        If String.IsNullOrWhiteSpace(txtFirstname.Text) OrElse cboRole.SelectedIndex = -1 Then
            txtUsername.Clear()
            Exit Sub
        End If

        Dim cleanFirst As String = txtFirstname.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim cleanRole As String = cboRole.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim shortRole As String = If(cleanRole.Length >= 4, cleanRole.Substring(0, 4), cleanRole)
        Dim suggestedUser As String = $"{cleanFirst}{shortRole}"

        If suggestedUser.Contains("admin") Then suggestedUser = $"{suggestedUser}usr"

        Try
            connection()
            Dim counter As Integer = 1
            Dim checkUser As String = suggestedUser

            Do
                sql = "SELECT Username FROM users WHERE LOWER(Username)=LOWER(@uname)"
                cmd = New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@uname", checkUser)
                dr = cmd.ExecuteReader()

                If Not dr.HasRows Then
                    dr.Close()
                    Exit Do
                End If
                dr.Close()

                checkUser = $"{suggestedUser}{counter}"
                counter += 1
            Loop

            txtUsername.Text = checkUser
            txtUsername.SelectionStart = txtUsername.TextLength
        Catch ex As Exception
            txtUsername.Text = $"{cleanFirst}{shortRole}"
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtUsername.KeyPress
        txtUsername.Tag = "ManualEdited"
    End Sub

    Private Sub txtLastname_TextChanged(sender As Object, e As EventArgs) Handles txtLastname.TextChanged
        If String.IsNullOrWhiteSpace(txtLastname.Text) Then
            SetFeedbackLabel(lblLastnameError, "Lastname is required.", True)
        ElseIf Not Regex.IsMatch(txtLastname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblLastnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblLastnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtFirstname_TextChanged(sender As Object, e As EventArgs) Handles txtFirstname.TextChanged
        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            SetFeedbackLabel(lblFirstnameError, "Firstname is required.", True)
        ElseIf Not Regex.IsMatch(txtFirstname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblFirstnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblFirstnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub cboDepartment_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboDepartment.SelectedIndexChanged
        If cboDepartment.SelectedIndex = -1 Then
            SetFeedbackLabel(lblDepartmentError, "Department is required.", True)
        Else
            SetFeedbackLabel(lblDepartmentError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtEmail_TextChanged(sender As Object, e As EventArgs) Handles txtEmail.TextChanged
        Dim val As String = txtEmail.Text.Trim().ToLower()

        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblEmailError, "Email is required.", True)
            Exit Sub
        End If

        Dim strictGmailRegex As New Regex("^[a-zA-Z0-9._%+-]+@gmail\.com$", RegexOptions.IgnoreCase)
        If Not strictGmailRegex.IsMatch(val) Then
            SetFeedbackLabel(lblEmailError, "Must end strictly with @gmail.com.", True)
            Exit Sub
        End If

        Try
            connection()
            Dim count As Integer = 0
            sql = "SELECT COUNT(*) FROM users WHERE LOWER(Email) = LOWER(@email)"
            Using localCmd As New MySqlCommand(sql, cn)
                localCmd.Parameters.AddWithValue("@email", val)
                count = Convert.ToInt32(localCmd.ExecuteScalar())
            End Using

            If count > 0 Then
                SetFeedbackLabel(lblEmailError, "Email address already registered!", True)
            Else
                SetFeedbackLabel(lblEmailError, "✓ OK", False)
            End If
        Catch ex As Exception
            SetFeedbackLabel(lblEmailError, "Error verifying email address.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_TextChanged(sender As Object, e As EventArgs) Handles txtUsername.TextChanged
        Dim val As String = txtUsername.Text.Trim()

        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblUsernameError, "Username is required.", True)
            Exit Sub
        End If

        If val.ToLower().Contains("admin") Then
            SetFeedbackLabel(lblUsernameError, "Usernames related to 'admin' are prohibited.", True)
            Exit Sub
        End If

        Try
            connection()
            Dim count As Integer = 0
            sql = "SELECT COUNT(*) FROM users WHERE LOWER(Username) = LOWER(@uname)"
            Using localCmd As New MySqlCommand(sql, cn)
                localCmd.Parameters.AddWithValue("@uname", val)
                count = Convert.ToInt32(localCmd.ExecuteScalar())
            End Using

            If count > 0 Then
                SetFeedbackLabel(lblUsernameError, "Username already taken!", True)
            Else
                SetFeedbackLabel(lblUsernameError, "✓ OK", False)
            End If
        Catch ex As Exception
            SetFeedbackLabel(lblUsernameError, "Error verifying username.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtPassword_TextChanged(sender As Object, e As EventArgs) Handles txtPassword.TextChanged, txtConfirmPass.TextChanged
        Dim hasUpper As Boolean = txtPassword.Text.Any(AddressOf Char.IsUpper)
        Dim hasLower As Boolean = txtPassword.Text.Any(AddressOf Char.IsLower)

        If String.IsNullOrWhiteSpace(txtPassword.Text) Then
            SetFeedbackLabel(lblConfirmPassError, "Password is required.", True)
        ElseIf Not hasUpper OrElse Not hasLower OrElse txtPassword.Text.Length < 6 Then
            SetFeedbackLabel(lblConfirmPassError, "Min 6 chars, uppercase & lowercase.", True)
        ElseIf txtPassword.Text <> txtConfirmPass.Text Then
            SetFeedbackLabel(lblConfirmPassError, "Passwords do not match.", True)
        Else
            SetFeedbackLabel(lblConfirmPassError, "✓ Passwords Match", False)
        End If
    End Sub

    Private Sub picUser_DoubleClick(sender As Object, e As EventArgs) Handles picUser.DoubleClick
        Using ofd As New OpenFileDialog()
            ofd.Filter = "Image Files (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png"
            If ofd.ShowDialog() = DialogResult.OK Then
                picUser.SizeMode = PictureBoxSizeMode.StretchImage

                If picUser.Image IsNot Nothing Then picUser.Image.Dispose()
                picUser.Image = Image.FromFile(ofd.FileName)

                Using ms As New MemoryStream()
                    picUser.Image.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg)
                    profileImageBytes = ms.ToArray()
                End Using

                SetFeedbackLabel(lblPictureError, "✓ Uploaded", False)
            End If
        End Using
    End Sub

    Private Sub btnSubmit_Click(sender As Object, e As EventArgs) Handles btnSubmit.Click
        If lblLastnameError.ForeColor = Color.Red OrElse lblFirstnameError.ForeColor = Color.Red OrElse
           lblEmailError.ForeColor = Color.Red OrElse lblUsernameError.ForeColor = Color.Red OrElse
           lblConfirmPassError.ForeColor = Color.Red OrElse lblDepartmentError.ForeColor = Color.Red Then

            MsgBox("Please resolve all validation errors before submitting!", MsgBoxStyle.Exclamation, "Validation Error")
            Return
        End If

        If cboDepartment IsNot Nothing AndAlso cboDepartment.SelectedIndex = -1 Then
            MsgBox("Please select a department!", MsgBoxStyle.Exclamation, "Validation Error")
            Return
        End If

        Dim fullName As String = $"{txtLastname.Text.Trim().ToUpper()}, {txtFirstname.Text.Trim().ToUpper()}"
        Dim freshStaffCode As String = GetNextStaffCode()

        Try
            connection()

            Dim uCount As Integer = 0
            sql = "SELECT COUNT(*) FROM users WHERE LOWER(Username) = LOWER(@uname)"
            Using cmdCheck1 As New MySqlCommand(sql, cn)
                cmdCheck1.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
                uCount = Convert.ToInt32(cmdCheck1.ExecuteScalar())
            End Using
            If uCount > 0 Then
                MsgBox("Username is already taken!", MsgBoxStyle.Critical, "Duplicate Error")
                CloseConnection()
                Return
            End If

            Dim eCount As Integer = 0
            sql = "SELECT COUNT(*) FROM users WHERE LOWER(Email) = LOWER(@email)"
            Using cmdCheck2 As New MySqlCommand(sql, cn)
                cmdCheck2.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())
                eCount = Convert.ToInt32(cmdCheck2.ExecuteScalar())
            End Using
            If eCount > 0 Then
                MsgBox("Email address is already registered!", MsgBoxStyle.Critical, "Duplicate Error")
                CloseConnection()
                Return
            End If

            sql = "INSERT INTO users (StaffCode, Username, Password, Lastname, Firstname, FullName, Department, Role, Email, Picture, AccountStatus, LoginAttempts) " &
                   "VALUES (@scode, @uname, @pass, @lname, @fname, @fullname, @dept, @role, @email, @pic, 'Active', 0)"

            cmd = New MySqlCommand(sql, cn)
            cmd.Parameters.AddWithValue("@scode", freshStaffCode)
            cmd.Parameters.AddWithValue("@uname", txtUsername.Text.Trim())
            cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
            cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@fullname", fullName)
            cmd.Parameters.AddWithValue("@dept", cboDepartment.Text.Trim())
            cmd.Parameters.AddWithValue("@role", cboRole.Text.ToUpper())
            cmd.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())

            If profileImageBytes IsNot Nothing Then
                cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = profileImageBytes
            Else
                cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = DBNull.Value
            End If

            cmd.ExecuteNonQuery()
            MsgBox("Successfully Registered New User!", MsgBoxStyle.Information, "Success")

            ClearForm()
            GenerateStaffCode()

        Catch ex As MySqlException
            If ex.Number = 1062 Then
                MsgBox("Database constraint conflict (Error 1062): " & ex.Message, MsgBoxStyle.Critical, "MySQL Index Conflict")
            Else
                MsgBox("Database Error: " & ex.Message, MsgBoxStyle.Critical, "Error")
            End If
        Catch ex As Exception
            MsgBox("Error: " & ex.Message, MsgBoxStyle.Critical, "Error")
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub ClearForm()
        txtLastname.Clear()
        txtFirstname.Clear()
        txtEmail.Clear()
        txtUsername.Clear()
        txtUsername.Tag = "AutoGenerated"
        txtPassword.Clear()
        txtConfirmPass.Clear()
        If cboRole.Items.Count > 0 Then cboRole.SelectedIndex = 0
        If cboDepartment IsNot Nothing Then cboDepartment.SelectedIndex = -1
        picUser.Image = Nothing
        profileImageBytes = Nothing
        ClearAllValidationLabels()
    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        If MsgBox("Are you sure you want to Cancel?", vbYesNo + MsgBoxStyle.Question, "Confirm Cancel") = MsgBoxResult.Yes Then
            ClearForm()
            Me.Hide()
            frmMain.Enabled = True
            frmMain.TopMost = True
            Me.TopMost = False
        End If
    End Sub

    Private Sub UpdateUsernameSuggestion(sender As Object, e As EventArgs) Handles txtFirstname.TextChanged, cboRole.SelectedIndexChanged

    End Sub
End Class